# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: build

on:
  push:
    tags:
      - "release-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: pnpm i
      - run: pnpm run lint
      - run: pnpm run build:lib

      - name: Prepare files for npm branch
        run: |
          mkdir -p deploy
          cp -r dist deploy/
          cp package.json LICENSE README.md deploy/

      - name: Deploy to npm branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: npm
